### ISSUE TITLE
Nothing renames Python script to app.py

### ISSUE THREAD

**Issue by gingerhax** [mrwadams/attackgen#3]
Script to run app is called "👋_Welcome.py" and does not get renamed during setup process. Changing the name to "app.py" and following the instructions to run the Streamlit program allows it to execute as normal.

**Comment by mrwadams** [comment]
Hi @gingerhax,

Thanks, I'd just spotted that myself when going back through the README. The initial page for the tool needs to remain as '👋_Welcome.py', since the file names are picked up by the multipage menu. It's a little weird I know, but it's a limitation of Streamlit.

I've updated the README file with the correct command.
